import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useState } from 'react';
import { mediaUrl, session } from '../../lib/api';
import { StarRating } from '../../components/ui/StarRating';
import type { FilmReview } from '../../types/domain';
import { FilmForm } from './FilmForm';
import { FilmReviewForm } from './FilmReviewForm';
import { adjustWatchCount, deleteFilm, getFilm } from './films';

const dateLabel = (date?: string) => date ? new Intl.DateTimeFormat('es-AR', { day: '2-digit', month: 'long', year: 'numeric' }).format(new Date(`${date}T12:00:00`)) : 'Todavía sin fecha';
export function FilmDetailPage() {
  const id = Number(useParams().id); const validId = Number.isInteger(id) && id > 0; const navigate = useNavigate(); const qc = useQueryClient();
  const [editing, setEditing] = useState(false); const [reviewing, setReviewing] = useState(false);
  const filmQuery = useQuery({ queryKey: ['film', id], queryFn: () => getFilm(id), enabled: validId });
  const count = useMutation({ mutationFn: (delta: number) => adjustWatchCount(id, delta, new Date().toLocaleDateString('sv-SE')), onSuccess: async () => { await Promise.all([qc.invalidateQueries({ queryKey: ['film', id] }), qc.invalidateQueries({ queryKey: ['films'] })]); } });
  const remove = useMutation({ mutationFn: () => deleteFilm(id), onSuccess: async () => { await qc.invalidateQueries({ queryKey: ['films'] }); navigate('/films'); } });
  if (!validId || filmQuery.isError) return <p className="form-error">No pudimos abrir esa película. Volvé a la sala e intentá otra vez.</p>;
  if (filmQuery.isLoading) return <p>Cargando película…</p>;
  if (!filmQuery.data) return <p className="form-error">No pudimos abrir esa película. Volvé a la sala e intentá otra vez.</p>;
  const film = filmQuery.data; const username = session.get()?.username; const ownReview = film.reviews.find(review => review.author === username); const reviewers = ['tomas', 'avril']; const reviewFor = (author: string) => film.reviews.find(review => review.author === author);
  return <section className="film-detail"><Link to="/films">← Volver a WhichFilm</Link><div className="film-detail__head"><div className="film-detail__poster">{film.posterUrl ? <img src={mediaUrl(film.posterUrl)} alt={`Póster de ${film.title}`} /> : <span>🎞️</span>}</div><div><p className="eyebrow">{film.releaseDate?.slice(0, 4) ?? 'SIN AÑO'} · {film.platform ? `${film.platform.icon} ${film.platform.name}` : 'PLATAFORMA PENDIENTE'}</p><h1>{film.title}</h1>{film.originalTitle && film.originalTitle !== film.title && <p className="original-title">{film.originalTitle}</p>}<div className="genre-pills genre-pills--detail">{film.genres.map(genre => <span key={genre}>{genre}</span>)}</div><p className="film-synopsis">{film.synopsis || 'Todavía no guardamos la sinopsis de esta película.'}</p></div><div className="detail-actions"><button className="secondary-button" onClick={() => setEditing(true)}>✎ Editar ficha</button><button className="main-button" onClick={() => setReviewing(true)}>★ Mi reseña</button></div></div><section className="watch-counter" aria-label="Contador de veces vistas"><div><p className="eyebrow">CONTADOR COMPARTIDO</p><h2>{film.watchedCount === 0 ? 'Todavía no la vieron' : `${film.watchedCount} ${film.watchedCount === 1 ? 'vez' : 'veces'}`}</h2><p>Última vista: {dateLabel(film.lastWatchedOn)}</p></div><div><button className="counter-button" aria-label="Restar una vista" disabled={film.watchedCount === 0 || count.isPending} onClick={() => count.mutate(-1)}>−</button><button className="counter-add" disabled={count.isPending} onClick={() => count.mutate(1)}>La vimos +1 🍿</button></div>{count.error && <p className="form-error">{count.error.message}</p>}</section><section className="reviews-section"><div className="section-title"><div><p className="eyebrow">DOS MIRADAS</p><h2>Reseñas</h2></div><strong>{film.reviews.length}/2</strong></div><div className="film-review-columns">{reviewers.map(author => { const review = reviewFor(author); return <ReviewCard key={author} author={author} review={review} own={author === username} onReview={() => setReviewing(true)} />; })}</div></section><button className="danger-button" disabled={remove.isPending} onClick={() => { if (window.confirm(`¿Eliminar “${film.title}” de WhichFilm?`)) remove.mutate(); }}>{remove.isPending ? 'Eliminando…' : 'Eliminar película'}</button>{remove.error && <p className="form-error">{remove.error.message}</p>}{editing && <FilmForm film={film} onClose={() => setEditing(false)} />}{reviewing && <FilmReviewForm film={film} review={ownReview} onClose={() => setReviewing(false)} />}</section>;
}
function ReviewCard({ author, review, own, onReview }: { author: string; review?: FilmReview; own: boolean; onReview: () => void }) { return <article className="film-review-card"><div><span className="review-avatar">{author[0].toUpperCase()}</span><h3>{author === 'tomas' ? 'Tomás' : 'Avril'} {own && <small>· vos</small>}</h3></div>{review ? <><StarRating label={`Puntuación de ${author}`} value={review.rating} /><p>{review.comment || 'Sin comentario todavía.'}</p><small>La vio: {dateLabel(review.watchedOn)}</small></> : <><p className="muted">Todavía no dejó su reseña.</p>{own && <button className="secondary-button" onClick={onReview}>Escribir la mía</button>}</>}</article>; }
