import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { ConfirmDialog } from '../../components/ui/ConfirmDialog';
import { Modal } from '../../components/ui/Modal';
import type { Home, HomeRecipe, HomeRecipeIngredient, MealType } from '../../types/domain';
import { deleteHomeRecipe, saveHomeRecipe, uploadHomeRecipePhoto } from './homeRecipes';

const meals: { value: MealType; label: string }[] = [{ value: 'DESAYUNO', label: 'Desayuno' }, { value: 'ALMUERZO', label: 'Almuerzo' }, { value: 'MERIENDA', label: 'Merienda' }, { value: 'CENA', label: 'Cena' }];
const emptyIngredient = (): HomeRecipeIngredient => ({ grams: 0, name: '' });

export function HomeRecipeForm({ home, recipe, copyOf, onClose, onDeleted }: { home: Home; recipe?: HomeRecipe; copyOf?: HomeRecipe; onClose: () => void; onDeleted?: () => void }) {
 const qc = useQueryClient();
 const source = recipe ?? copyOf;
 const [selectedHome, setSelectedHome] = useState<Home>(source?.home ?? home);
 const [ingredients, setIngredients] = useState<HomeRecipeIngredient[]>(source?.ingredients.length ? source.ingredients : [emptyIngredient()]);
 const [file, setFile] = useState<File>();
 const [confirmingDelete, setConfirmingDelete] = useState(false);
 const invalidate = () => Promise.all([qc.invalidateQueries({ queryKey: ['home-recipes', 'TOMAS'] }), qc.invalidateQueries({ queryKey: ['home-recipes', 'AVRIL'] }), ...(recipe ? [qc.invalidateQueries({ queryKey: ['home-recipe', recipe.id] })] : [])]);
 const save = useMutation({ mutationFn: async (form: FormData) => { const saved = await saveHomeRecipe({ home: selectedHome, name: String(form.get('name')).trim(), recipeUrl: String(form.get('recipeUrl')).trim() || undefined, preparedOn: String(form.get('preparedOn')), mealType: String(form.get('mealType')) as MealType, ingredients: ingredients.filter(ingredient => ingredient.name.trim()).map(ingredient => ({ ...ingredient, name: ingredient.name.trim() })), copyPhotoFromId: copyOf?.id }, recipe?.id); return file ? uploadHomeRecipePhoto(saved.id, file) : saved; }, onSuccess: async () => { await invalidate(); onClose(); } });
 const remove = useMutation({ mutationFn: () => deleteHomeRecipe(recipe!.id), onSuccess: async () => { await invalidate(); if (onDeleted) onDeleted(); else onClose(); } });
 const updateIngredient = (index: number, value: Partial<HomeRecipeIngredient>) => setIngredients(current => current.map((ingredient, position) => position === index ? { ...ingredient, ...value } : ingredient));
 if (confirmingDelete && recipe) return <ConfirmDialog title="¿Borrar esta receta?" message="La receta y su foto dejarán de estar disponibles en la casa." confirmLabel="Borrar receta" pending={remove.isPending} onClose={() => setConfirmingDelete(false)} onConfirm={() => remove.mutate()} />;
 return <Modal onClose={onClose}><form className="home-recipe-form" onSubmit={event => { event.preventDefault(); save.mutate(new FormData(event.currentTarget)); }}><p className="eyebrow">{recipe ? 'EDITAR RECETA' : copyOf ? 'REPETIR RECETA' : 'RECETA CASERA'}</p><h2>{recipe ? 'Ajustemos la receta' : copyOf ? 'Volvamos a prepararla' : '¿Qué cocinaron hoy?'}</h2><fieldset className="home-picker"><legend>¿En qué casa?</legend>{(['TOMAS', 'AVRIL'] as Home[]).map(value => <label key={value}><input type="radio" name="home" checked={selectedHome === value} onChange={() => setSelectedHome(value)} /><span>{value === 'TOMAS' ? '🏠 Casa de Tomás' : '🏡 Casa de Avril'}</span></label>)}</fieldset><label>Nombre<input name="name" defaultValue={source?.name} placeholder="Ej. Risotto de hongos" required autoFocus /></label><div className="form-columns"><label>Fecha<input name="preparedOn" type="date" defaultValue={recipe?.preparedOn ?? new Date().toLocaleDateString('sv-SE')} required /></label><label>Momento<select name="mealType" defaultValue={source?.mealType ?? 'CENA'}>{meals.map(meal => <option key={meal.value} value={meal.value}>{meal.label}</option>)}</select></label></div><label>URL de la receta <small className="tiny">Opcional</small><input name="recipeUrl" type="url" defaultValue={source?.recipeUrl} placeholder="https://…" /></label><fieldset className="ingredient-fields"><legend>Ingredientes</legend>{ingredients.map((ingredient, index) => <div className="ingredient-row" key={index}><label>Gramos<input type="number" min="0" inputMode="numeric" value={ingredient.grams} onChange={event => updateIngredient(index, { grams: Number(event.target.value) })} required /></label><label>Ingrediente<input value={ingredient.name} onChange={event => updateIngredient(index, { name: event.target.value })} placeholder="Ej. arroz" required /></label>{ingredients.length > 1 && <button className="text-button" type="button" onClick={() => setIngredients(current => current.filter((_, position) => position !== index))} aria-label="Quitar ingrediente">Quitar</button>}</div>)}<button className="secondary-button" type="button" onClick={() => setIngredients(current => [...current, emptyIngredient()])}>+ Agregar ingrediente</button></fieldset><label>Foto del plato<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => setFile(event.target.files?.[0])} /></label>{file && <img className="form-photo-preview" src={URL.createObjectURL(file)} alt="Vista previa de la receta" />}<button className="main-button" disabled={save.isPending || remove.isPending}>{save.isPending ? 'Guardando…' : recipe ? 'Guardar cambios' : 'Guardar receta'} ✦</button>{recipe && <button className="danger-button" type="button" disabled={save.isPending || remove.isPending} onClick={() => setConfirmingDelete(true)}>Borrar receta</button>}{(save.error || remove.error) && <p className="form-error">{(save.error || remove.error)!.message}</p>}</form></Modal>;
}
