import { api } from '../../lib/api';
import type { Cooking, CookingReview, Home, MealType, Recipe, RecipeIngredient, RecipeStep } from '../../types/domain';

export type RecipeInput = { name: string; sourceUrl?: string; ingredients: RecipeIngredient[]; steps: RecipeStep[] };
export type CookingInput = { home: Home; servings: number; cookedOn: string; mealType: MealType };
export const getRecipes = (search?: string) => api<Recipe[]>(`/how-cook/recipes${search ? `?${new URLSearchParams({ search })}` : ''}`);
export const getRecipe = (id: number) => api<Recipe>(`/how-cook/recipes/${id}`);
export const saveRecipe = (input: RecipeInput, id?: number) => api<Recipe>(`/how-cook/recipes${id ? `/${id}` : ''}`, { method: id ? 'PUT' : 'POST', body: JSON.stringify(input) });
export const deleteRecipe = (id: number) => api<void>(`/how-cook/recipes/${id}`, { method: 'DELETE' });
export const getCookings = (filters: { home?: Home; recipeId?: number } = {}) => { const query = new URLSearchParams(); if (filters.home) query.set('home', filters.home); if (filters.recipeId) query.set('recipeId', String(filters.recipeId)); return api<Cooking[]>(`/how-cook/cookings${query.size ? `?${query}` : ''}`); };
export const getCooking = (id: number) => api<Cooking>(`/how-cook/cookings/${id}`);
export const createCooking = (recipeId: number, input: CookingInput) => api<Cooking>(`/how-cook/recipes/${recipeId}/cookings`, { method: 'POST', body: JSON.stringify(input) });
export const updateCooking = (id: number, input: CookingInput) => api<Cooking>(`/how-cook/cookings/${id}`, { method: 'PUT', body: JSON.stringify(input) });
export const deleteCooking = (id: number) => api<void>(`/how-cook/cookings/${id}`, { method: 'DELETE' });
export const uploadCookingPhoto = (id: number, file: File) => { const data = new FormData(); data.append('file', file); return api<Cooking>(`/how-cook/cookings/${id}/photos`, { method: 'POST', body: data }); };
export const setCookingCover = (cookingId: number, photoId: number) => api<Cooking>(`/how-cook/cookings/${cookingId}/cover/${photoId}`, { method: 'PUT' });
export const deleteCookingPhoto = (photoId: number) => api<void>(`/how-cook/cooking-photos/${photoId}`, { method: 'DELETE' });
export const createCookingReview = (cookingId: number, input: Pick<CookingReview, 'rating' | 'comment'>) => api<CookingReview>(`/how-cook/cookings/${cookingId}/reviews`, { method: 'POST', body: JSON.stringify(input) });
export const updateCookingReview = (reviewId: number, input: Pick<CookingReview, 'rating' | 'comment'>) => api<CookingReview>(`/how-cook/cooking-reviews/${reviewId}`, { method: 'PUT', body: JSON.stringify(input) });
export const deleteCookingReview = (reviewId: number) => api<void>(`/how-cook/cooking-reviews/${reviewId}`, { method: 'DELETE' });
