import { useQuery,useMutation,useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { getAllCategories,saveCategory } from './categories';
import { getHighlightTags, saveHighlightTag } from '../places/highlightTags';
import type { Category, HighlightTag } from '../../types/domain';
type CategoryDraft = Pick<Category, 'name' | 'icon' | 'active'>;
const emptyCategory:CategoryDraft={name:'',icon:'✨',active:true};
const emptyTag={name:'',emoji:'✨'};
export function CategoryManager(){
 const qc=useQueryClient(); const list=useQuery({queryKey:['categories','all'],queryFn:getAllCategories}); const tags=useQuery({queryKey:['highlight-tags'],queryFn:getHighlightTags});
 const [draft,setDraft]=useState<CategoryDraft>(emptyCategory); const [editing,setEditing]=useState<number>(); const [tagDraft,setTagDraft]=useState<Omit<HighlightTag,'id'>>(emptyTag); const [editingTag,setEditingTag]=useState<number>();
 const categoryMutation=useMutation({mutationFn:()=>saveCategory({...draft,slug:draft.name.trim().toLocaleLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')},editing),onSuccess:()=>{qc.invalidateQueries({queryKey:['categories']});setDraft(emptyCategory);setEditing(undefined)}});
 const tagMutation=useMutation({mutationFn:()=>saveHighlightTag(tagDraft,editingTag),onSuccess:()=>{qc.invalidateQueries({queryKey:['highlight-tags']});setTagDraft(emptyTag);setEditingTag(undefined)}});
 return <section className="settings-page"><p className="eyebrow">CONFIGURACIÓN COMPARTIDA</p><h2>Rubros y etiquetas</h2><p className="intro">Avril y Tomas pueden mantener este catálogo. Los rubros definen el tipo de lugar; las etiquetas cuentan por qué vale la pena ir.</p>
 <div className="settings-grid"><div><h3>Rubros</h3><form className="inline-form category-settings-form" onSubmit={e=>{e.preventDefault();categoryMutation.mutate()}}><input placeholder="Nombre del rubro" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} required/><input aria-label="Ícono" placeholder="✨" value={draft.icon} onChange={e=>setDraft({...draft,icon:e.target.value})} required/><button className="main-button">{editing?'Guardar':'Agregar'}</button></form><div className="category-list">{list.data?.map(c=><span key={c.id}>{c.icon} {c.name}{!c.active&&' (inactiva)'} <button className="text-button" onClick={()=>{setEditing(c.id);setDraft({name:c.name,icon:c.icon,active:c.active})}}>Editar</button><button className="text-button" onClick={()=>saveCategory({...c,active:!c.active},c.id).then(()=>qc.invalidateQueries({queryKey:['categories']}))}>{c.active?'Desactivar':'Activar'}</button></span>)}</div></div>
 <div><h3>Etiquetas destacadas</h3><form className="inline-form tag-settings-form" onSubmit={e=>{e.preventDefault();tagMutation.mutate()}}><input aria-label="Emoji" placeholder="✨" value={tagDraft.emoji} onChange={e=>setTagDraft({...tagDraft,emoji:e.target.value})} required/><input placeholder="Nombre de etiqueta" value={tagDraft.name} onChange={e=>setTagDraft({...tagDraft,name:e.target.value})} required/><button className="main-button">{editingTag?'Guardar':'Agregar'}</button></form><div className="category-list">{tags.data?.map(tag=><span key={tag.id}>{tag.emoji} {tag.name} <button className="text-button" onClick={()=>{setEditingTag(tag.id);setTagDraft({name:tag.name,emoji:tag.emoji})}}>Editar</button></span>)}</div></div></div></section>}
